// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDee1HzE4fFTpOv6horghNPBJtJmLFd8Tk',
    appId: '1:1070342136336:web:99bb3a0f64fab0daa7a095',
    messagingSenderId: '1070342136336',
    projectId: 'ecomapp-mt-stripe',
    authDomain: 'ecomapp-mt-stripe.firebaseapp.com',
    storageBucket: 'ecomapp-mt-stripe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNuf_oF-GBxN0VRwBOg69O5HXNGGtVBJs',
    appId: '1:1070342136336:android:e43aabad9098a412a7a095',
    messagingSenderId: '1070342136336',
    projectId: 'ecomapp-mt-stripe',
    storageBucket: 'ecomapp-mt-stripe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWEC9J0RhrbgDxpzZXY2rURGejqo-nt1Y',
    appId: '1:1070342136336:ios:f561d7b1392764e6a7a095',
    messagingSenderId: '1070342136336',
    projectId: 'ecomapp-mt-stripe',
    storageBucket: 'ecomapp-mt-stripe.firebasestorage.app',
    iosBundleId: 'com.ecomapp.ecomapp',
  );
}
